[package]
name = "pallet-authentication"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "MIT"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }

[features]
default = ["std"]
std = ["codec/std"]
